### ISSUE TITLE
Recover drawNomNomlDiagram function

### ISSUE THREAD

**Issue by AntonioMateoGomez** [arrow-kt/arrow-site#24]
We should recover the Type Class Hierarchy as it was done in 0.9 arrow version

**Comment by rachelcarmena** [comment]
Fixed by:
* Recover files: https://github.com/arrow-kt/arrow-site/pull/23
* Move directories:
   * arrow-kt/arrow-core#55
   * arrow-kt/arrow-fx#81
   * https://github.com/arrow-kt/arrow-optics/pull/26
   * https://github.com/arrow-kt/arrow-incubator/pull/57
